source ${__BCHSHELL__}/posix/__dunders__.sh
__source__ ${__BCHSHELL__}/posix/misc
__source__ ${__BCHSHELL__}/posix/init/venv.sh
__source__ ${__BCHSHELL__}/zsh/init/omzsh.sh
__source__ ${__BCHSHELL__}/zsh/main.sh

export PROJECT_HOME=~/dev
source virtualenvwrapper.sh
