root=$(dirname $(dirname $0))
source ${root}/posix/__dunders__

__source__ ${root}/posix/venv.sh
__source__ ${root}/posix/misc
#__source__ $(dirname $0)/zprofile.omzsh
__source__ $(dirname $0)/zshrc.main

compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION
